// USER STATUS:
export const USER_HAS_ERRORED = 'USER_HAS_ERRORED';
export const USER_IS_LOADING = 'USER_IS_LOADING';
export const USER_CHECK_STATUS_SUCCESS = 'USER_CHECK_STATUS_SUCCESS';

// OPENING AND CLOSING MODALS:
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// ADDING A BOOKMARK:
export const BOOKMARK_HAS_ERRORED = 'BOOKMARK_HAS_ERRORED';
export const BOOKMARK_IS_LOADING = 'BOOKMARK_IS_LOADING';
export const BOOKMARK_STATUS_SUCCESS = 'BOOKMARK_STATUS_SUCCESS';
export const BOOKMARK_SHOW_ADD = 'BOOKMARK_SHOW_ADD';
export const BOOKMARK_SHOW_PREVIEW = 'BOOKMARK_SHOW_PREVIEW';
export const BOOKMARK_SHOW_EDIT = 'BOOKMARK_SHOW_EDIT';
export const BOOKMARK_FIELDS_SUCCESS = 'BOOKMARK_FIELDS_SUCCESS';

// CREATING A PROJECT:
export const CREATE_PROJECT_SHOW_ADD_DETAILS = 'CREATE_PROJECT_SHOW_ADD_DETAILS';
export const CREATE_PROJECT_SHOW_NEW_PROJECT_FORM = 'CREATE_PROJECT_SHOW_NEW_PROJECT_FORM';
export const CREATE_PROJECT_HAS_ERRORED = 'CREATE_PROJECT_HAS_ERRORED';
export const DATA_WITHIN_CREATE_PROJECT_IS_LOADING = 'DATA_WITHIN_CREATE_PROJECT_IS_LOADING';

export const LOAD_BOOKMARK_SCRAPE = 'LOAD_BOOKMARK_SCRAPE';

export const SAVE_BOOKMARK = 'SAVE_BOOKMARK';
/////////


export const PROJECTS_LIST_HAS_ERRORED = 'PROJECTS_LIST_HAS_ERRORED';
export const PROJECTS_LIST_IS_LOADING = 'PROJECTS_LIST_IS_LOADING';
export const PROJECTS_LIST_SUCCESS = 'PROJECTS_LIST_SUCCESS';

export const PROJECT_HAS_ERRORED = 'PROJECT_HAS_ERRORED';
export const PROJECT_IS_LOADING = 'PROJECT_IS_LOADING';
export const PROJECT_SUCCESS = 'PROJECT_SUCCESS';

export const NEW_EXPLORATIVE_NODE_CREATED = 'NEW_EXPLORATIVE_NODE_CREATED';

export const NEW_LINK_CREATED = 'NEW_LINK_CREATED';

export const CLEAR_PROJECT_DATA = 'CLEAR_PROJECT_DATA';
