export const USER_HAS_ERRORED = 'USER_HAS_ERRORED';
export const USER_IS_LOADING = 'USER_IS_LOADING';
export const USER_CHECK_STATUS_SUCCESS = 'USER_CHECK_STATUS_SUCCESS';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';