export const USER_HAS_ERRORED = 'USER_HAS_ERRORED';
export const USER_IS_LOADING = 'USER_IS_LOADING';
export const USER_CHECK_STATUS_SUCCESS = 'USER_CHECK_STATUS_SUCCESS';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const BOOKMARK_HAS_ERRORED = 'BOOKMARK_HAS_ERRORED';
export const BOOKMARK_IS_LOADING = 'BOOKMARK_IS_LOADING';
export const BOOKMARK_STATUS_SUCCESS = 'BOOKMARK_STATUS_SUCCESS';
export const BOOKMARK_SHOW_ADD = 'BOOKMARK_SHOW_ADD';
export const BOOKMARK_SHOW_PREVIEW = 'BOOKMARK_SHOW_PREVIEW';
export const BOOKMARK_SHOW_EDIT = 'BOOKMARK_SHOW_EDIT';
export const BOOKMARK_FIELDS_SUCCESS = 'BOOKMARK_FIELDS_SUCCESS';

export const LOAD_BOOKMARK_SCRAPE = 'LOAD_BOOKMARK_SCRAPE';
export const BOOKMARK_SAVE = 'BOOKMARK_SAVE';
